# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{

  # install all firmware by default
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  hardware.graphics = {
      enable = true;

      extraPackages = with pkgs; [
      intel-media-driver
      libva-vdpau-driver
      intel-vaapi-driver
      # intel-media-driver
      # libvdpau-va-gl
      # libva-vdpau-driver
      ];

      # extraPackages32 = with pkgs.driversi686Linux; [
      #   intel-media-driver
      #   libva-vdpau-driver
      # ];
  };

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;
  hardware.bluetooth.powerOnBoot = true;


  fileSystems."/" = {
      device = "/dev/disk/by-uuid/eefb6952-45d1-48b6-8fc2-26cfbfefe774";
      fsType = "ext4";
  };

  fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/1CB7-11C4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a1348622-c6f7-461e-a119-a0a41f5c9f75"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
