# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  # install all firmware by default
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod"];

  boot.initrd.kernelModules = ["i915"];
  boot.kernelParams = [ "i915.enable_guc=3" ];

  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  hardware.graphics = {
    enable = true;

    extraPackages = [
      pkgs.intel-media-driver
      pkgs.intel-compute-runtime
      (pkgs.vpl-gpu-rt or pkgs.onevpl-intel-gpu)
    ];

    extraPackages32 = [pkgs.driversi686Linux.intel-media-driver];
  };

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8e331926-c408-4d5a-baa1-c66641f0ef3c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2C3B-E32B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/ffa00982-8abe-4024-b019-e39087b015b3";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
